name: deploy-app

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying app..."

